/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <lockdownd/lockdownd-Structs.h>
#import <lockdownd/MSUBootFirmwareUpdater.h>

@class DevNodeWriter;

@interface ASPStorageiBootUpdater : MSUBootFirmwareUpdater {

	DevNodeWriter* _llbWriter;
	DevNodeWriter* _firmwareWriter;

}

@property (retain) DevNodeWriter * firmwareWriter;              //@synthesize firmwareWriter=_firmwareWriter - In the implementation block
@property (retain) DevNodeWriter * llbWriter;                   //@synthesize llbWriter=_llbWriter - In the implementation block
-(id)initWithApNonce:(id)arg1 ;
-(BOOL)updateBootFirmwareWithError:(id*)arg1 ;
-(BOOL)updateBootFirmwareWithCallback:(ramrod_update_callbacks*)arg1 context:(firmware_update_context*)arg2 error:(id*)arg3 ;
-(void)dealloc;
-(DevNodeWriter *)llbWriter;
-(void)setLlbWriter:(DevNodeWriter *)arg1 ;
-(DevNodeWriter *)firmwareWriter;
-(void)setFirmwareWriter:(DevNodeWriter *)arg1 ;
@end

