/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <lockdownd/lockdownd-Structs.h>
#import <lockdownd/MSUBootFirmwareUpdater.h>

@class IOServiceWriter;

@interface IMG3NorUpdater : MSUBootFirmwareUpdater {

	IOServiceWriter* _writer;

}

@property (retain) IOServiceWriter * writer;              //@synthesize writer=_writer - In the implementation block
-(id)initWithApNonce:(id)arg1 ;
-(BOOL)updateBootFirmwareWithCallback:(ramrod_update_callbacks*)arg1 context:(firmware_update_context*)arg2 error:(id*)arg3 ;
-(BOOL)_encodeAndWriteIMG3Data:(CFDataRef)arg1 isLLB:(BOOL)arg2 isTicket:(BOOL)arg3 withError:(id*)arg4 ;
-(void)dealloc;
-(IOServiceWriter *)writer;
-(void)setWriter:(IOServiceWriter *)arg1 ;
@end

