/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <lockdownd/IOServiceWriter.h>

@interface IODualSPIWriter : IOServiceWriter {

	BOOL _usesAFUH;
	unsigned _spiDriverConnect;
	char* _regBuffer;

}

@property (assign) unsigned spiDriverConnect;                       //@synthesize spiDriverConnect=_spiDriverConnect - In the implementation block
@property (assign) char* regBuffer;                                 //@synthesize regBuffer=_regBuffer - In the implementation block
@property (getter=doesUseAFUH,readonly) BOOL usesAFUH;              //@synthesize usesAFUH=_usesAFUH - In the implementation block
-(id)initWithService:(unsigned)arg1 ;
-(int)writeData:(id)arg1 withError:(id*)arg2 ;
-(int)openService;
-(id)_getSFRManifestHashForPayload:(id)arg1 ;
-(BOOL)_headerMatchesBootSFRManifestHash:(id)arg1 ;
-(int)writeNewerGenerationFirmware:(id)arg1 withError:(id*)arg2 ;
-(int)writeFirstGenerationFirmware:(id)arg1 withError:(id*)arg2 ;
-(int)commitHeaderAtIndex:(unsigned long long)arg1 withError:(id*)arg2 ;
-(int)commitPreparedHeaderWithError:(id*)arg1 ;
-(unsigned long long)findPreparedHeader;
-(id)findHeaders;
-(id)readDataAtOffset:(unsigned)arg1 ofLength:(unsigned)arg2 ;
-(BOOL)verifyHeadersAtIndex:(unsigned long long)arg1 ;
-(BOOL)verifyFirmwareAtIndex:(unsigned long long)arg1 againstData:(id)arg2 ;
-(int)readDataAtOffset:(unsigned)arg1 ofLength:(unsigned)arg2 intoBuffer:(void*)arg3 ;
-(int)eraseBytes:(unsigned)arg1 ofLength:(unsigned)arg2 withError:(id*)arg3 ;
-(int)_writeFirmware:(id)arg1 toHeader:(id)arg2 withError:(id*)arg3 ;
-(int)_commitHeader:(id)arg1 withError:(id*)arg2 ;
-(BOOL)_checkUsesAFUH;
-(BOOL)doesUseAFUH;
-(int)_writeBytes:(char*)arg1 atOffset:(unsigned)arg2 ofLength:(unsigned)arg3 withError:(id*)arg4 ;
-(int)_commitBytes:(char*)arg1 atOffset:(unsigned)arg2 ofLength:(unsigned)arg3 withError:(id*)arg4 ;
-(void)dealloc;
-(unsigned)spiDriverConnect;
-(void)setSpiDriverConnect:(unsigned)arg1 ;
-(char*)regBuffer;
-(void)setRegBuffer:(char*)arg1 ;
@end

