/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol OS_dispatch_semaphore;
@class CUPairingSession, NSMutableDictionary, NSObject;

@interface LockdownSRPState : NSObject {

	BOOL _pairingSessionStarted;
	int _retval;
	CUPairingSession* _pairingSession;
	NSMutableDictionary* _srpResponse;
	NSObject*<OS_dispatch_semaphore> _sem;

}

@property (assign,nonatomic) int retval;                                          //@synthesize retval=_retval - In the implementation block
@property (nonatomic,retain) CUPairingSession * pairingSession;                   //@synthesize pairingSession=_pairingSession - In the implementation block
@property (assign,nonatomic) BOOL pairingSessionStarted;                          //@synthesize pairingSessionStarted=_pairingSessionStarted - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * srpResponse;                   //@synthesize srpResponse=_srpResponse - In the implementation block
@property (nonatomic,readonly) NSObject*<OS_dispatch_semaphore> sem;              //@synthesize sem=_sem - In the implementation block
-(id)init;
-(void)invalidate;
-(int)retval;
-(void)setRetval:(int)arg1 ;
-(CUPairingSession *)pairingSession;
-(void)setPairingSession:(CUPairingSession *)arg1 ;
-(BOOL)pairingSessionStarted;
-(void)setPairingSessionStarted:(BOOL)arg1 ;
-(NSMutableDictionary *)srpResponse;
-(void)setSrpResponse:(NSMutableDictionary *)arg1 ;
-(NSObject*<OS_dispatch_semaphore>)sem;
@end

