/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


#import <lockdownd/lockdownd-Structs.h>
@class NSArray, NSData;

@interface MSUBootFirmwareUpdater : NSObject {

	BOOL _isErase;
	BOOL _shouldCommit;
	unsigned _matchedService;
	NSArray* _bootBlockImages;
	NSArray* _firmwareImages;
	NSData* _apNonce;
	NSData* _daliData;
	NSData* _ibootData;
	NSData* _llbData;
	NSData* _ans2Data;
	NSData* _logoData;

}

@property (retain) NSData * daliData;                      //@synthesize daliData=_daliData - In the implementation block
@property (retain) NSData * ibootData;                     //@synthesize ibootData=_ibootData - In the implementation block
@property (retain) NSData * ans2Data;                      //@synthesize ans2Data=_ans2Data - In the implementation block
@property (retain) NSData * logoData;                      //@synthesize logoData=_logoData - In the implementation block
@property (retain) NSArray * bootBlockImages;              //@synthesize bootBlockImages=_bootBlockImages - In the implementation block
@property (retain) NSArray * firmwareImages;               //@synthesize firmwareImages=_firmwareImages - In the implementation block
@property (assign) unsigned matchedService;                //@synthesize matchedService=_matchedService - In the implementation block
@property (assign) BOOL isErase;                           //@synthesize isErase=_isErase - In the implementation block
@property (assign) BOOL shouldCommit;                      //@synthesize shouldCommit=_shouldCommit - In the implementation block
@property (retain) NSData * apNonce;                       //@synthesize apNonce=_apNonce - In the implementation block
@property (retain) NSData * llbData;                       //@synthesize llbData=_llbData - In the implementation block
+(id)updaterForDevice;
+(id)updaterForServiceNamed:(id)arg1 ;
+(BOOL)supportsDualiBoot;
+(BOOL)supportsDualSPINAND;
+(BOOL)requiresSEPInFW;
+(BOOL)isSingleStageBoot;
+(id)_orderedServiceNames;
+(id)_orderedClasses;
+(id)_serviceToClasses;
+(Class)_classForMatchedServiceName:(id)arg1 ;
+(unsigned)_determineDeviceService;
+(unsigned)_waitForServiceNamed:(id)arg1 ;
-(id)initWithApNonce:(id)arg1 ;
-(void)dealloc;
-(BOOL)updateBootFirmwareWithError:(id*)arg1 ;
-(BOOL)updateBootFirmwareWithCallback:(ramrod_update_callbacks*)arg1 context:(firmware_update_context*)arg2 error:(id*)arg3 ;
-(id)matchedServiceName;
-(BOOL)generateFirmwareImagesWithCallback:(ramrod_update_callbacks*)arg1 context:(firmware_update_context*)arg2 ;
-(id)_restoreInfoDictionary;
-(int)_encodeAndWriteFirmware:(id)arg1 toWriter:(id)arg2 withError:(id*)arg3 ;
-(id)_encodeFirmware:(id)arg1 withRestoreInfo:(id)arg2 ;
-(NSArray *)bootBlockImages;
-(void)setBootBlockImages:(NSArray *)arg1 ;
-(NSArray *)firmwareImages;
-(void)setFirmwareImages:(NSArray *)arg1 ;
-(unsigned)matchedService;
-(void)setMatchedService:(unsigned)arg1 ;
-(BOOL)isErase;
-(void)setIsErase:(BOOL)arg1 ;
-(BOOL)shouldCommit;
-(void)setShouldCommit:(BOOL)arg1 ;
-(NSData *)apNonce;
-(void)setApNonce:(NSData *)arg1 ;
-(NSData *)daliData;
-(void)setDaliData:(NSData *)arg1 ;
-(NSData *)ibootData;
-(void)setIbootData:(NSData *)arg1 ;
-(NSData *)llbData;
-(void)setLlbData:(NSData *)arg1 ;
-(NSData *)ans2Data;
-(void)setAns2Data:(NSData *)arg1 ;
-(NSData *)logoData;
-(void)setLogoData:(NSData *)arg1 ;
@end

