/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <lockdownd/MSUiBootHeaderV1.h>

@interface MSUiBootHeaderV2 : MSUiBootHeaderV1 {

	unsigned _headerVersion;
	char* _headerSignature;
	char* _headerHash;
	char* _headerReserved;

}

@property (assign,nonatomic) char* headerSignature;              //@synthesize headerSignature=_headerSignature - In the implementation block
@property (assign,nonatomic) char* headerHash;                   //@synthesize headerHash=_headerHash - In the implementation block
@property (assign,nonatomic) char* headerReserved;               //@synthesize headerReserved=_headerReserved - In the implementation block
@property (assign) unsigned headerVersion;                       //@synthesize headerVersion=_headerVersion - In the implementation block
-(id)initWithIOServiceWriter:(id)arg1 ;
-(void)setHeaderHash:(char*)arg1 ;
-(void)setHeaderReserved:(char*)arg1 ;
-(void)setHeaderSignature:(char*)arg1 ;
-(id)packStructure;
-(BOOL)loadHeaderAtOffset:(unsigned)arg1 ;
-(void)setAsFirstGeneration;
-(unsigned)length;
-(void)invalidate;
-(BOOL)isValid;
-(BOOL)validHeaderSignature;
-(void)makeValid;
-(BOOL)validHash;
-(id)computeHash;
-(id)_hashDataWithNativeHashMethod:(id)arg1 ;
-(id)_hashData:(id)arg1 withMethod:(id)arg2 ;
-(id)description;
-(void)dealloc;
-(char*)headerSignature;
-(char*)headerHash;
-(unsigned)headerVersion;
-(void)setHeaderVersion:(unsigned)arg1 ;
-(char*)headerReserved;
@end

