/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <lockdownd/MSUiBootHeader.h>

@interface MSUiBootHeaderV1 : MSUiBootHeader {

	unsigned _valid;

}

@property (assign) unsigned valid;              //@synthesize valid=_valid - In the implementation block
-(id)packStructure;
-(BOOL)loadHeaderAtOffset:(unsigned)arg1 ;
-(void)invalidate;
-(void)setAsFirstGeneration;
-(void)makeValid;
-(unsigned)length;
-(id)description;
-(BOOL)isValid;
-(long long)compareTo:(id)arg1 ;
-(unsigned)valid;
-(void)setValid:(unsigned)arg1 ;
@end

