/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:42:59 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/lockdownd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

#import <lockdownd/lockdownd-Structs.h>
#import <lockdownd/MSUBootFirmwareUpdater.h>

@class DevNodeWriter;

@interface NVMEiBootUpdater : MSUBootFirmwareUpdater {

	DevNodeWriter* _writer;

}

@property (retain) DevNodeWriter * writer;              //@synthesize writer=_writer - In the implementation block
-(id)initWithApNonce:(id)arg1 ;
-(void)dealloc;
-(BOOL)generateFirmwareImagesWithCallback:(ramrod_update_callbacks*)arg1 context:(firmware_update_context*)arg2 ;
-(BOOL)updateBootFirmwareWithCallback:(ramrod_update_callbacks*)arg1 context:(firmware_update_context*)arg2 error:(id*)arg3 ;
-(BOOL)_copyIBICFromPath:(char*)arg1 withOptions:(CFDictionaryRef)arg2 intoArray:(const _CFArray*)arg3 withError:(_CFError*)arg4 ;
-(DevNodeWriter *)writer;
-(void)setWriter:(DevNodeWriter *)arg1 ;
@end

